In [2]:
import pandas as pd
import numpy as np

In [3]:
df_users = pd.read_csv("./users_final.csv")

In [4]:
df_users

,Unnamed: 0,Mal ID,Username,Gender,Birthday,Location,Joined,Days Watched,Watching,Completed,On Hold,Dropped,Plan to Watch,Total Entries,Rewatched,Episodes Watched,Last Online
0,0,1,Xinil,Male,1985-03-04T00:00:00+00:00,California,2004-11-05T00:00:00+00:00,142.3,1.0,233.0,8.0,93.0,64.0,399.0,60.0,8458.0,2018-05-14 18:02:55
1,1,3,Aokaado,Male,1988-11-11 00:00:00,"Oslo, Norway",2004-11-11T00:00:00+00:00,68.6,23.0,137.0,99.0,44.0,40.0,343.0,15.0,4072.0,2016-07-28 10:39:03
2,2,4,Crystal,Female,1989-01-10 00:00:00,"Melbourne, Australia",2004-11-13T00:00:00+00:00,212.8,16.0,636.0,303.0,0.0,45.0,1000.0,10.0,12781.0,2018-05-14 13:04:48
3,3,9,Arcane,NaN,NaN,NaN,2004-12-05T00:00:00+00:00,30.0,5.0,54.0,4.0,3.0,0.0,66.0,0.0,1817.0,NaN
4,4,18,Mad,NaN,NaN,NaN,2005-01-03T00:00:00+00:00,52.0,1.0,114.0,10.0,5.0,23.0,153.0,42.0,3038.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
731285,731285,1291083,Dolopa,NaN,NaN,NaN,2012-05-06T00:00:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
731286,731286,1291085,alenrobnik,NaN,NaN,NaN,2012-05-06T00:00:00+00:00,21.4,16.0,58.0,9.0,1.0,42.0,126.0,0.0,1239.0,NaN
731287,731287,1291087,Oblongata,NaN,1993-01-30T00:00:00+00:00,NaN,2012-05-06T00:00:00+00:00,51.3,38.0,175.0,0.0,9.0,211.0,433.0,2.0,3010.0,NaN
731288,731288,1291091,Etnota,NaN,NaN,NaN,2012-05-06T00:00:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
731289,731289,1291097,JuunanaSai,Female,NaN,NaN,2012-05-06T00:00:00+00:00,3.7,1.0,11.0,0.0,0.0,2.0,14.0,0.0,222.0,NaN

In [5]:
df_users.columns

Index(['Unnamed: 0', 'Mal ID', 'Username', 'Gender', 'Birthday', 'Location',
       'Joined', 'Days Watched', 'Watching', 'Completed', 'On Hold', 'Dropped',
       'Plan to Watch', 'Total Entries', 'Rewatched', 'Episodes Watched',
       'Last Online'],
      dtype='object')

In [6]:
df_users = df_users[['Mal ID', 'Username','Location','Completed','Dropped','Plan to Watch','Watching']]

In [7]:
df_users.columns

Index(['Mal ID', 'Username', 'Location', 'Completed', 'Dropped',
       'Plan to Watch', 'Watching'],
      dtype='object')

In [8]:
df_users

,Mal ID,Username,Location,Completed,Dropped,Plan to Watch,Watching
0,1,Xinil,California,233.0,93.0,64.0,1.0
1,3,Aokaado,"Oslo, Norway",137.0,44.0,40.0,23.0
2,4,Crystal,"Melbourne, Australia",636.0,0.0,45.0,16.0
3,9,Arcane,NaN,54.0,3.0,0.0,5.0
4,18,Mad,NaN,114.0,5.0,23.0,1.0
...,...,...,...,...,...,...,...
731285,1291083,Dolopa,NaN,0.0,0.0,0.0,0.0
731286,1291085,alenrobnik,NaN,58.0,1.0,42.0,16.0
731287,1291087,Oblongata,NaN,175.0,9.0,211.0,38.0
731288,1291091,Etnota,NaN,0.0,0.0,0.0,0.0
731289,1291097,JuunanaSai,NaN,11.0,0.0,2.0,1.0

In [9]:
nuevos_nombres = {'Mal ID':'ID_USER','Username':'USERNAME','Location': 'LOCATION',
                 'Completed':'COMPLETED','Dropped':'DROPPED','Plan to Watch':'PLAN_TO_WATCH',
                 'Watching':'WATCHING'}
df_users = df_users.rename(columns=nuevos_nombres)

In [10]:
df_users

,ID_USER,USERNAME,LOCATION,COMPLETED,DROPPED,PLAN_TO_WATCH,WATCHING
0,1,Xinil,California,233.0,93.0,64.0,1.0
1,3,Aokaado,"Oslo, Norway",137.0,44.0,40.0,23.0
2,4,Crystal,"Melbourne, Australia",636.0,0.0,45.0,16.0
3,9,Arcane,NaN,54.0,3.0,0.0,5.0
4,18,Mad,NaN,114.0,5.0,23.0,1.0
...,...,...,...,...,...,...,...
731285,1291083,Dolopa,NaN,0.0,0.0,0.0,0.0
731286,1291085,alenrobnik,NaN,58.0,1.0,42.0,16.0
731287,1291087,Oblongata,NaN,175.0,9.0,211.0,38.0
731288,1291091,Etnota,NaN,0.0,0.0,0.0,0.0
731289,1291097,JuunanaSai,NaN,11.0,0.0,2.0,1.0

In [11]:
df_users.isna().sum()

ID_USER               0
USERNAME              1
LOCATION         577447
COMPLETED             8
DROPPED               8
PLAN_TO_WATCH         8
WATCHING              8
dtype: int64

In [12]:
#Akihabara, Bolivia, Estados Unidos
specific_values=["Japón","Estados Unidos","Bolivia"]
df_users['LOCATION'].fillna(np.random.choice(specific_values), inplace=True)

In [13]:
df_users.dtypes

ID_USER            int64
USERNAME          object
LOCATION          object
COMPLETED        float64
DROPPED          float64
PLAN_TO_WATCH    float64
WATCHING         float64
dtype: object

In [14]:
df_users['USERNAME'].fillna(value='unknow', inplace=True)
df_users['COMPLETED'].fillna(value=0, inplace=True)
df_users['DROPPED'].fillna(value=0, inplace=True)
df_users['PLAN_TO_WATCH'].fillna(value=0, inplace=True)
df_users['WATCHING'].fillna(value=0, inplace=True)

In [15]:
df_users.isna().sum()

ID_USER          0
USERNAME         0
LOCATION         0
COMPLETED        0
DROPPED          0
PLAN_TO_WATCH    0
WATCHING         0
dtype: int64

In [16]:
df_users.to_csv('./USERS.csv', index=False)